# Generated by Django 5.0.7 on 2024-08-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
