# Generated by Django 5.0.7 on 2024-08-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_userdetails_remove_order_username_order_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
